#-------------------------------------------------------------------------------
# Lint & Completion

[[plugins]]
repo = 'mattn/emmet-vim'


#-------------------------------------------------------------------------------
# View 

[[plugins]]
repo = 'simeji/winresizer'

[[plugins]]
repo = 'arcticicestudio/nord-vim'
hook_add = '''
  colorscheme nord
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
  let g:lightline = {'colorscheme': 'nord'}
'''

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'Yggdroot/indentLine'


#-------------------------------------------------------------------------------
# Syntax

[[plugins]]
on_ft = 'toml'
repo = 'cespare/vim-toml'

[[plugins]]
on_ft = 'typescript'
repo = 'leafgarland/typescript-vim'

[[plugins]]
on_ft = 'typescript'
repo = 'peitalin/vim-jsx-typescript'

[[plugins]]
on_ft = 'typescript'
repo = 'maxmellon/vim-jsx-pretty'

[[plugins]]
repo = 'KabbAmine/vCoolor.vim'

[[plugins]]
on_ft = 'tex'
repo = 'lervag/vimtex'
hook_add = '''
  let g:vimtex_syntax_enabled = 0
  let g:vimtex_fold_enabled = 1
'''

[[plugins]]
repo = 'n-eq/mbed-vim'
